##################################################
#
# BORG
# Raw PHP tests
#
##################################################
server {
	listen 80 default_server;
    server_name borg.home;
	index index.php index.htm index.html;

	root /var/www/borg.home;

	error_log  /var/log/nginx/error.log;
	access_log /var/log/nginx/access.log;

	location ~ \.php$ {
		try_files $uri =404;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass php:9000;
		fastcgi_index index.php;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
	}

    location ~ ^/alina/(.*)$ {
        try_files $uri $uri/ /alina/index.php?alinapath=$1&$args;
    }
}

server {
	listen 443 ssl default_server;
	ssl on;
    ssl_certificate /srv/sewa/cert002/borg.home/borg.home.crt;
    ssl_certificate_key /srv/sewa/cert002/borg.home/borg.home.key;
	listen [::]:443 ssl;
    server_name borg.home;
	index index.php index.htm index.html;

	root /var/www/borg.home;

	error_log  /var/log/nginx/error.log;
	access_log /var/log/nginx/access.log;

	location / {
		# Handle OPTIONS requests for CORS preflight
		if ($request_method = OPTIONS) {
			add_header 'Access-Control-Allow-Origin' '*';
			add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
			add_header 'Access-Control-Allow-Headers' 'DNT, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Range';
			add_header 'Access-Control-Max-Age' 1728000;
			add_header 'Content-Type' 'text/plain; charset=utf-8';
			add_header 'Content-Length' 0;
			return 204; # Return No Content for OPTIONS request success
		}
	}

	location ~ \.php$ {
		try_files $uri =404;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass php:9000;
		fastcgi_index index.php;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
	}

    location ~ ^/alina/(.*)$ {
        try_files $uri $uri/ /alina/index.php?alinapath=$1&$args;
    }

	location ~ \.(js|png|jpg|jpeg|gif|ico|html|woff|woff2|ttf|svg|eot|otf)$ {
        add_header "Access-Control-Allow-Origin" "*";
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
        try_files $uri /noimage.png;
    }

	location ~ \.(css)$ {
		# Handle OPTIONS preflight request
		if ($request_method = OPTIONS) {
			add_header 'Access-Control-Allow-Origin' '*';
			add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
			add_header 'Access-Control-Allow-Headers' 'Content-Type, X-Custom-Token'; # List any custom headers
			add_header 'Access-Control-Max-Age' 86400; # Cache preflight for 24 hours
			return 204;
		}

		# Add CORS header for the actual GET request
		add_header 'Access-Control-Allow-Origin' '*';
		
		# ... caching and try_files ...
		expires 1M;
		access_log off;
		add_header Cache-Control "public";
		try_files $uri /noimage.png;
	}

}