server {
    listen 80 default_server;
    server_name borg.home;
    return 301 https://$host$request_uri;  # Редирект на HTTPS

	location ~* \.(js|css|png|jpg|jpeg|gif|ico|html|woff|woff2|ttf|svg|eot|otf)$ {
        add_header Access-Control-Allow-Origin "*";
        add_header Access-Control-Allow-Methods "GET, HEAD";
        add_header Access-Control-Allow-Headers "Content-Type";
        
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
        try_files $uri =404;  # Корректная обработка 404
    }
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl;
    server_name borg.home;

    ssl_certificate /srv/sewa/cert002/borg.home/borg.home.crt;
    ssl_certificate_key /srv/sewa/cert002/borg.home/borg.home.key;

    index index.php index.htm index.html;
    root /var/www/borg.home;

    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    # Общие CORS‑заголовки для всех статических ресурсов
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|html|woff|woff2|ttf|svg|eot|otf)$ {
        add_header Access-Control-Allow-Origin "*";
        add_header Access-Control-Allow-Methods "GET, HEAD";
        add_header Access-Control-Allow-Headers "Content-Type";
        
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
        try_files $uri =404;  # Корректная обработка 404
    }

    # PHP‑обработка
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Специальный маршрут для alina
    location ~ ^/alina/(.*)$ {
        try_files $uri $uri/ /alina/index.php?alinapath=$1&$args;
    }

    # Корневой маршрут (если нужно)
    location / {
        try_files $uri $uri/ =404;
    }
}
