FROM python:3.5
#Labels as key value pair
LABEL Maintainer="Vsevolod Azovsky"
WORKDIR /srv/python/app1
###COPY /docker/python/app1/requirements.txt ./
###RUUN pip install -r ./requirements.txt

#CMD instruction should be used to run the software
#contained by your image, along with any arguments.

###CMD [ "python", "./main.py"]

