networks:
  s2_net:
    name: s2_net
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      config:
        - subnet: 10.0.11.0/24
          gateway: 10.0.11.1

services:
  nginx:
    container_name: s2_nginx
    hostname: nginx
    networks:
      s2_net:
        ipv4_address: 10.0.11.10
    restart: unless-stopped
    env_file: .env
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./server/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./server/var/log/nginx:/var/log/nginx
      - ./server/srv/sewa:/srv/sewa
      - ./server/var/www:/var/www

  php:
    container_name: s2_php
    hostname: php
    networks:
      s2_net:
        ipv4_address: 10.0.11.11
    restart: unless-stopped
    env_file: .env
    build: ./docker/php
    volumes:
      # php.ini
      - ./server/usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini
      # /var/www
      - ./server/var/www:/var/www
      # OWN FILES
      - ./server/root/sewa:/root/sewa
    working_dir: /var/www/zero.home

  mysql:
    container_name: s2_mysql
    hostname: mysql
    networks:
      s2_net:
        ipv4_address: 10.0.11.12
    restart: unless-stopped
    env_file: .env
    image: mysql:8.0.27
    command: mysqld --sql_mode="IGNORE_SPACE,STRICT_TRANS_TABLES" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=0
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
